name: Testing 
run-name: ${{ github.actor }} is running tests 🚀
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.17', '1.18', '1.19']
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - run : go get golang.org/x/lint/golint

      - name: Run make 
        run: make

